### ISSUE TITLE
这个APK解密报错

### ISSUE THREAD

**Issue by BeastMachines** [newdive/uzmap-resource-extractor#3]
https://a.app.qq.com/o/simple.jsp?pkgname=com.xingshiwu.app

环境:python3.7 windows
使用命令: python3 -v com.xingshiwu.app_1.0.4_11.apk
报错信息
Traceback (most recent call last):
  File "D:/Desktop/uzmap-resource-extractor-master/main.py", line 33, in <module>
    extractMap = tools.decryptAllResourcesInApk(args[0],outputFolder,printLog=True)
  File "D:\Desktop\uzmap-resource-extractor-master\tools.py", line 227, in decryptAllResourcesInApk
    rc4Key = extractRC4KeyFromApk(apkFilePath)
  File "D:\Desktop\uzmap-resource-extractor-master\tools.py", line 175, in extractRC4KeyFromApk
    rc4Key = extractRC4Key(soContent)
  File "D:\Desktop\uzmap-resource-extractor-master\tools.py", line 37, in extractRC4Key
    dataSection,dataContent = elffile.get_section_by_name('.rodata'),None
  File "D:\py3_venv\lib\site-packages\elftools\elf\elffile.py", line 105, in get_section_by_name
    for i, sec in enumerate(self.iter_sections()):
  File "D:\py3_venv\lib\site-packages\elftools\elf\elffile.py", line 114, in iter_sections
    yield self.get_section(i)
  File "D:\py3_venv\lib\site-packages\elftools\elf\elffile.py", line 93, in get_section
    section_header = self._get_section_header(n)
  File "D:\py3_venv\lib\site-packages\elftools\elf\elffile.py", line 468, in _get_section_header
    stream_pos=self._section_offset(n))
  File "D:\py3_venv\lib\site-packages\elftools\common\utils.py", line 39, in struct_parse
    stream.seek(stream_pos)
  File "D:\Python37\lib\zipfile.py", line 1025, in seek
    self._fileobj.seek(self._orig_compress_start)
  File "D:\Python37\lib\zipfile.py", line 704, in seek
    if self.writing():
AttributeError: '_SharedFile' object has no attribute 'writing'

**Comment by BeastMachines** [comment]
找到原因了，python3.7的zipfile有BUG，使用python3.8就没问题了

**Comment by newdive** [comment]
你好，目前发现python3.7.0的zipfile实现有误( 应该调用'_writing'方法，却调用了未定义的'writing'方法)，导致解析出错，多谢指出，已经做了Fix。
后续有问题/建议 欢迎继续提issue
